ALTER TABLE public.ads ADD COLUMN IF NOT EXISTS match_keywords text[], ADD COLUMN IF NOT EXISTS link_text text;

INSERT INTO public.ads (name, format, placement, image_url, alt_text, is_active, link_text, match_keywords, link) VALUES
('Gymgrossisten hantlar','equipment_link','exercise_equipment','',null,true,'Hantlar',ARRAY['hantlar','hantel'],'https://clk.tradedoubler.com/click?p=70361&a=3465011&g=17342194&url=https%3A%2F%2Fwww.gymgrossisten.com%2Futrustning-och-tillbehor%2Fhemmagym%2Fhantlar'),
('Gymgrossisten skivstänger','equipment_link','exercise_equipment','',null,true,'Skivstänger och viktskivor',ARRAY['skivstång'],'https://clk.tradedoubler.com/click?p=70361&a=3465011&g=17342194&url=https%3A%2F%2Fwww.gymgrossisten.com%2Futrustning-och-tillbehor%2Fhemmagym%2Fskivstanger'),
('Gymgrossisten kettlebells','equipment_link','exercise_equipment','',null,true,'Kettlebells',ARRAY['kettlebell'],'https://clk.tradedoubler.com/click?p=70361&a=3465011&g=17342194&url=https%3A%2F%2Fwww.gymgrossisten.com%2Futrustning-och-tillbehor%2Fhemmagym%2Fkettlebell'),
('Gymgrossisten träningsbänkar','equipment_link','exercise_equipment','',null,true,'Träningsbänkar',ARRAY['bänk'],'https://clk.tradedoubler.com/click?p=70361&a=3465011&g=17342194&url=https%3A%2F%2Fwww.gymgrossisten.com%2Futrustning-och-tillbehor%2Fhemmagym%2Ftraningsbankar'),
('Gymgrossisten gummiband','equipment_link','exercise_equipment','',null,true,'Gummiband och träningsband',ARRAY['gummiband'],'https://clk.tradedoubler.com/click?p=70361&a=3465011&g=17342194&url=https%3A%2F%2Fwww.gymgrossisten.com%2Futrustning-och-tillbehor%2Fgummiband-och-traningsband'),
('Gymgrossisten kroppsviktsträning','equipment_link','exercise_equipment','',null,true,'Chins- och dipsställningar',ARRAY['räcke','chins','dips'],'https://clk.tradedoubler.com/click?p=70361&a=3465011&g=17342194&url=https%3A%2F%2Fwww.gymgrossisten.com%2Futrustning-och-tillbehor%2Fhemmagym%2Fkroppsviktstraning'),
('Gymgrossisten träningsställningar','equipment_link','exercise_equipment','',null,true,'Träningsställningar',ARRAY['ställning'],'https://clk.tradedoubler.com/click?p=70361&a=3465011&g=17342194&url=https%3A%2F%2Fwww.gymgrossisten.com%2Futrustning-och-tillbehor%2Fhemmagym%2Ftraningsstallningar'),
('Gymgrossisten maghjul','equipment_link','exercise_equipment','',null,true,'Maghjul och bålträning',ARRAY['hjul'],'https://clk.tradedoubler.com/click?p=70361&a=3465011&g=17342194&url=https%3A%2F%2Fwww.gymgrossisten.com%2Futrustning-och-tillbehor%2Fhemmagym%2Fbalans-och-balstyrka'),
('Gymgrossisten träningsmattor','equipment_link','exercise_equipment','',null,true,'Träningsmattor',ARRAY['ingen'],'https://clk.tradedoubler.com/click?p=70361&a=3465011&g=17342194&url=https%3A%2F%2Fwww.gymgrossisten.com%2Futrustning-och-tillbehor%2Fhemmagym%2Ftraningsmattor');